apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: medusa-ingress
  namespace: medusa
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: medusa.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: medusa-storefront
                port:
                  number: 3000
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: medusa-backend
                port:
                  number: 9000
