apiVersion: v1
kind: Service
metadata:
  name: medusa-backend
  namespace: medusa
spec:
  selector:
    app: medusa-backend
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: medusa-storefront
  namespace: medusa
spec:
  selector:
    app: medusa-storefront
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
